# COS method for European call option pricing under the Heston model
# The convergence of the COS method price as the number of terms N increases.
# The implied volatility smile generated by the Heston model using COS pricing.

# The COS method (Fourier-Cosine expansion method) is a fast and accurate numerical technique for option pricing, 
# especially under models with known characteristic functions such as the Heston stochastic volatility model. 
# It approximates the option price by expanding the characteristic function of the log-asset price in a 
# Fourier-cosine series and integrating against the payoff function.

# COS Method Overview:
# The COS method expands the density function of the log-price in cosine series over a finite interval.
# The option price is computed as a weighted sum of cosine coefficients of the payoff function multiplied 
# by the characteristic function evaluated at specific frequencies.
# It converges rapidly and is computationally efficient compared to numerical integration or Monte Carlo.

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import brentq
from scipy.optimize import root 
from scipy.optimize import minimize
from scipy.stats import norm

# Heston characteristic function
def heston_char_func(u, params, S0, r, T):
    kappa, theta, sigma, rho, v0 = params
    x0 = np.log(S0)
    a = kappa * theta
    b = kappa
    d = np.sqrt((rho * sigma * 1j * u - b)**2 + sigma**2 * (1j * u + u**2))
    g = (b - rho * sigma * 1j * u - d) / (b - rho * sigma * 1j * u + d)
    exp1 = 1j * u * (x0 + r * T)
    exp2 = (a / sigma**2) * ((b - rho * sigma * 1j * u - d) * T - 2 * np.log((1 - g * np.exp(-d * T)) / (1 - g)))
    exp3 = (v0 / sigma**2) * (b - rho * sigma * 1j * u - d) * (1 - np.exp(-d * T)) / (1 - g * np.exp(-d * T))
    return np.exp(exp1 + exp2 - exp3)

# COS coefficients for call payoff
def cos_coefficients_call(a, b, k):
    c = np.ones_like(k)
    c[0] = 0.5
    chi = (np.cos(k * np.pi * (b - a) / (b - a)) * np.exp(b) - np.cos(k * np.pi * (0 - a) / (b - a)) * np.exp(0) +
           (k * np.pi / (b - a)) * (np.sin(k * np.pi * (b - a) / (b - a)) * np.exp(b) - np.sin(k * np.pi * (0 - a) / (b - a)) * np.exp(0))) / (1 + (k * np.pi / (b - a))**2)
    psi = np.zeros_like(k, dtype=float)
    psi[1:] = (b - a) / (k[1:] * np.pi) * (np.sin(k[1:] * np.pi * (b - a) / (b - a)) - np.sin(k[1:] * np.pi * (0 - a) / (b - a)))
    psi[0] = b - 0
    Vk = chi - psi
    return c * Vk

# COS method price calculation
def cos_method_price(S0, K, T, r, params, N=128, L=10):
    a = -L * np.sqrt(T)
    b = L * np.sqrt(T)
    k = np.arange(N)
    u = k * np.pi / (b - a)
    char_vals = heston_char_func(u, params, S0, r, T)
    Vk = cos_coefficients_call(a, b, k)
    temp = np.exp(-1j * u * a) * char_vals
    price = np.exp(-r * T) * K * np.sum(Vk * temp.real)
    return float(price)

# Black-Scholes implied vol calculation
def get_implied_vol(price, S0, K, T, r):
    def bs_obj(sigma):
        d1 = (np.log(S0 / K) + (r + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))
        d2 = d1 - sigma * np.sqrt(T)
        return S0 * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2) - price
    try:
        # x = brentq(bs_obj, 1e-9, 1)
        sol = root(bs_obj,x0)
        #sol = minimize(bs_obj,x0,bounds=[(0, 10)])
        x = sol.x
        return x
    except:
        return np.nan

# Parameters
S0 = 100
r = 0.03
T = 0.3
x0 = 0.1
params = [2.0, 0.2, 0.3, -0.7, 0.04]  # kappa, theta, sigma, rho, v0
strikes = np.linspace(10, 140, 30)

# Plot convergence of COS method price for a fixed strike
strike_test = 100
N_values = np.arange(10, 300, 10)
prices = [cos_method_price(S0, strike_test, T, r, params, N=n) for n in N_values]

plt.figure(figsize=(10, 5))
plt.plot(N_values, prices, marker='o')
plt.title('COS Method Price Convergence (Strike = 100)')
plt.xlabel('Number of COS Terms (N)')
plt.ylabel('Option Price')
plt.grid(True)
plt.show()

# Calculate implied volatilities for strikes using COS method
prices = np.array([cos_method_price(S0, K, T, r, params, N=256) for K in strikes])
implied_vols = [get_implied_vol(p, S0, K, T, r) for p, K in zip(prices, strikes)]

plt.figure(figsize=(10, 5))
plt.plot(strikes, implied_vols, 'b-', marker='o')
plt.title('Heston Model Implied Volatility Smile via COS Method')
plt.xlabel('Strike')
plt.ylabel('Implied Volatility')
plt.grid(True)